export const SALADS_FETCHED = 'SALADS_FETCHED';
export const SALADS_LOADING = 'SALADS_LOADING';
export const SALADS_FAILD = 'SALADS_FAILD';

export const MOLECULES_FETCHED = 'MOLECULES_FETCHED';
export const MOLECULES_LOADING = 'MOLECULES_LOADING';
export const MOLECULES_FAILD = 'MOLECULES_FAILD';



export const  ADD_TO_CARTE='ADD_TO_CARTE'
export const  UPT_IN_CARTE='UPT_IN_CARTE'
